### ISSUE TITLE
Support for newline regex

### ISSUE THREAD

**Issue by jeroenooms** [mholt/PapaParse#289] opened 2016-02-10 13:17 UTC
My application needs to support csv files with either `\r\n` or `\n` linebreaks. Given that you already use [`input.split(newline)`](https://github.com/mholt/PapaParse/blob/4.1.0/papaparse.js#L972) we could easily split using the standard linebreak regex: `newline : /\r?\n/`.

However it looks like currently you are [overriding](https://github.com/mholt/PapaParse/blob/4.1.0/papaparse.js#L941-L943) it to be `\n`. What is the reason for this? Would you be willing to support a default linebreak of `/\r?\n/` so that both types of line endings are supported?

**Comment by mholt** [comment] 2016-02-10 15:54
A file with mixed line endings?

That sounds like a nightmare.

It makes delimiter auto-detection difficult and regex tend to slow things down. Have you benchmarked if it would take a hit?

**Comment by jeroenooms** [comment] 2016-02-10 15:55
No i didn't mean mixed line endings. I meant that users can upload csv files, and it will work regardless of which line endings their csv has.

**Comment by mholt** [comment] 2016-02-10 15:56
You can set the line ending or Papa will detect it otherwise. If it was set to an invalid sequence (not \r, \n, or \r\n), it will override it back to \n, the default.

**Comment by jeroenooms** [comment] 2016-02-10 16:02
Well that doesn't seem to work with [my csv data](http://web.ohmage.org/~snolen/sample_classes/01sample_class.csv). Papa detects wrong because it interprets the `\r\n` sequences as empty lines. It would be nice if you at least let me use `newline : /\r?\n/` in the config to get the proper behavior.

**Comment by mholt** [comment] 2016-02-10 16:07
I suspect it's unable to detect it properly because you have more empty lines than you do data lines. I'd just set it manually if you have messy files.

**Comment by jeroenooms** [comment] 2016-02-10 16:09
Manually to what? I need to support both the case of `\r\n` and `\n` files and I can't set it to a regex.

**Comment by mholt** [comment] 2016-02-10 16:12
If you set it to \n you can strip any remaining \r out. Papa just parses it; it won't attempt to clean up or change your data (except for the few very common cases where it can skip empty lines, etc). Cleaning up the data is up to the user.

**Comment by aron-helser** [comment] 2016-03-11 17:11
On a Windows box, PapaParse won't accept a file with just `\n` line endings when I allow auto-detected newlines - the parsing fails. Is auto-detection based on OS, or on the file contents?

It would be really helpful to allow a user to supply a file with either style line ending.

**Comment by jdpagley** [comment] 2016-05-18 20:09
I'm running into this issue as well. I need to support `\r\n` and `\n`.

**Comment by pokoli** [comment] 2017-01-16 11:58
I'm closing it as the solution have been already explained on https://github.com/mholt/PapaParse/issues/289#issuecomment-182451591

**Closed by pokoli** 2017-01-16 11:58 UTC

**Comment by xuan9230** [comment] 2017-10-25 23:42
@mholt When exporting from Excel/Numbers (I'm on a Mac) the line always ends with both endings. This nightmare does happen a lot - and newline auto-detect fails sometimes.

**Comment by pokoli** [comment] 2017-10-26 07:16
@xuan9230 any ideas on how to improve it?

**Comment by xuan9230** [comment] 2017-10-26 08:03
@pokoli Like mentioned above, allow regex for newline will be a solution.

**Comment by pokoli** [comment] 2017-10-26 08:26
@xuan9230 I will prefer to not include a regex as It will introduce some side effect. 

Indeed I don't see any problem with the example file you posted. I tested on the papa demo and it worked perfectly: It readed 190 rows, which is the same as I get when opening with libreoffice.

**Comment by xuan9230** [comment] 2017-10-26 22:37
@pokoli Hmm that's interesting... my papa(4.3.6) cannot detect newline and throws error:
![screen shot 2017-10-27 at 9 31 23 am](https://user-images.githubusercontent.com/6060740/32080160-e2f61492-baf9-11e7-9e2a-0e0794f1bee8.png)

Newline character is both` \r` and `\n` but detected as "", thus there are 46 data rows with `__parsed_extra`.

Does my config looks correct?
```
{
                header: true,
                skipEmptyLines: true,
                complete: (results) => console.log(results)
              }
```

**Comment by pokoli** [comment] 2017-10-27 06:57
Errors are only raised when the header row is marked. I've looked at the first error and it's not related with the newline, but the error is that there is comma on the text which is not escaped and this the parser thinks it's a new field.

**Comment by xuan9230** [comment] 2017-10-30 00:56
@pokoli Totally understood, but I do think this error is caused by the newline character, because of two reasons:
1. Only the values containing a linebreak at the beginning will lead to wrong interpretations of escaping commas, like this row:
```
{name: "↵"Strata Plan 35121", address: "  343 Sydney Rd"", notes: "343 Sydney Rd, Balgowlah, NSW 2093", __parsed_extra: Array(1)}
```
Whereas commas in other values are escaped correctly.

2. In `meta`, `linebreak` is shown as "", not correct `\r` or `\n`

**Comment by pokoli** [comment] 2017-11-02 08:41
@xuan9230 because the new line break character is included inside the text. So for me is a different issue and newline regex will not fix it.

**Comment by nandita1** [comment] 2023-03-29 12:53
I'm facing the same issue when the header has the delimiter as `\r\n` and columns have the delimiter as `\n`.
Can we atleast support autodetecting these two common delimiters?

**Comment by UlyssesInvictus** [comment] 2024-09-26 17:53
Still running into the same issue as well. Only solution I can really see is to parse the file as a string and grep the newlines first, but that defeats the purpose of leaving it up to a library in the first place.
