### ISSUE TITLE
 Can't resolve 'stream' in myapp\node_modules\papaparse

### ISSUE THREAD

**Issue by CP-Ram** [mholt/PapaParse#533] opened 2018-07-06 09:01 UTC
I'm using papaparse@4.4.0 with angular-cli@6.0.8
package.json file

> {
>   "name": "myapp",
>   "private": true,
>   "version": "0.0.0",
>   "main": "dist/app/server/main.js",
>   "scripts": {
      ...
      ....
>   },
>   "dependencies": {
>     "@angular/animations": "^6.0.0",
>     "@angular/cdk": "^6.0.1",
>     "@angular/common": "^6.0.0",
>     "@angular/compiler": "^6.0.0",
>     "@angular/core": "^6.0.0",
>     "@angular/forms": "^6.0.0",
>     "@angular/http": "^6.0.0",
>     "@angular/material": "^6.0.1",
>     "@angular/platform-browser": "^6.0.0",
>     "@angular/platform-browser-dynamic": "^6.0.0",
>     "@angular/platform-server": "^6.0.0",
>     "@angular/router": "^6.0.0",
>     "@nguniversal/aspnetcore-engine": "^6.0.0",
>     "@nguniversal/express-engine": "^6.0.0",
>     "@nguniversal/module-map-ngfactory-loader": "^6.0.0"
> 	...
> 	...
>     "node": "^8.11.3",
>     **"papaparse": "^4.4.0",**
> 	...
> 	...
>     "rxjs": "^6.0.0",
>     "rxjs-compat": "^6.2.1"
>     "tslint": "^5.10.0",
>     "tslint-loader": "^3.6.0"
>     "typings": "^2.1.1"
>   },
>   "devDependencies": {
>     "@angular-devkit/build-angular": "~0.6.0",
>     "@angular/cli": "~6.0.0",
>     "@angular/compiler-cli": "^6.0.0",
>     "@angular/language-service": "^6.0.0",
>     "@angularclass/hmr": "^2.1.3",
>     "@types/chai": "^4.1.4",
>     "@types/core-js": "^2.5.0"
>     "@types/jasmine": "^2.8.8",
>     "@types/jasminewd2": "^2.0.3",
>     "@types/jspdf": "^1.1.31",
>     "@types/kurento-utils": "^6.7.0",
>     "@types/loader-utils": "^1.1.3",
>     "@types/node": "~8.9.4"
>     "@types/webpack-env": "^1.13.6",
>    ..
>    ...
>   }
> }

in angular Component:
**import { Papa } from 'papaparse';**

while ng build getting the following error on window console
**ERROR in ./node_modules/papaparse/papaparse.js
Module not found: Error: Can't resolve 'stream' in 'C:\Bizruntime\AI\code\angular-universal\myappcustomer\myapp\node_modules\papaparse'**

**Comment by pokoli** [comment] 2018-07-06 10:01
This is a duplicate of #517 as the error is exactly the same. You should use the workarrounds discussed on this issue in order to be able to build papaparjse in angular

**Closed by pokoli** 2018-07-06 10:01 UTC
