### ISSUE TITLE
worker: true, Papa.SCRIPT_PATH and webpack lazy loading

### ISSUE THREAD

**Issue by doque** [mholt/PapaParse#563] opened 2018-09-03 08:23 UTC
Hello,

We're using `Papa.parse()` in a React component and would like to take advantage of the `worker: true` functionality in order to not freeze the user's browsers while parsing.
If I understand everything correctly, I have to lazy-load the file containing the Papaparse code (in this case, a simple ES6 class with no references to React/window/etc), which I'm doing by using Webpack's `import()`:
```js
case 'csv': {
  const {CsvParser} = await import('../utils/csv-parser');`
  const stuff = new CsvParser(csv).getStuff();
}
```

When running the parser, I'm facing this error:

`Uncaught (in promise) Error: Script path cannot be determined automatically when Papa Parse is loaded asynchronously. You need to set Papa.SCRIPT_PATH manually.`

`Papaparse` is used inside the lazy-loaded file:
```js
// utils/csv-parser.js

import Papa from 'papaparse';

getStuff() {
  // should I set Papa.SCRIPT_PATH here?
  const { data, errors } = Papa.parse(content, {
    header: true,
    worker: true
  });
}
```
What value do I set for `SCRIPT_PATH`? Is it the webpack module id for the papaparse dependency?
Using `require.resolve('papaparse')` yields `node_modules/papaparse/papaparse.js`, which can't be the right value for the browser.

**Comment by bahtou** [comment] 2018-10-16 15:44
Any help with the above? Same issue here. Thank you.

**Comment by pokoli** [comment] 2018-10-16 18:17
I'm closing this as duplicate of #566 reopen if you don't agree

**Closed by pokoli** 2018-10-16 18:17 UTC
