### ISSUE TITLE
input.substr is not a function

### ISSUE THREAD

**Issue by frankFree** [mholt/PapaParse#389] opened 2017-06-05 07:36 UTC
when i use, the error is 'input.substr is not a function'

**Comment by pokoli** [comment] 2017-06-05 07:49
HI @frankFree,

Thanks for reporting the issue. Could you explain a little bit how do you get this error? Do you have some pice of code that we can reproduce it? Which type of argument are you passing as input?

**Comment by osmangoninahid** [comment] 2017-06-13 07:20
I've already faced with same issue my code is 

 ```
Papa.parse(this.state.file,{
            complete : function(results){
                console.log(results);
            }
        })
```

in this state I have my file from input .

**Comment by pokoli** [comment] 2017-06-13 07:41
Which is the type of this.state.file? For me the problem is that you are not passing the correct type. See the [docs](http://papaparse.com/docs#csv-to-json) for full reference
Can you provide the full code of your example?

**Comment by osmangoninahid** [comment] 2017-06-13 08:23
I'm using in ReactJS with webpack, Here when I enter a file my  `onFileSelected` method is called here is my code  @pokoli 
 ```onFileSelected(e){
        e.preventDefault();
        let reader = new FileReader();
        let file = e.target.files[0];

        reader.onloadend = () => {
            Papa.parse(file,{
            header: true,
            complete : function(results){
                console.log(results);
            }
        })
        };

        reader.readAsDataURL(file);
    }
       ```

**Comment by osmangoninahid** [comment] 2017-06-13 10:10
Hey @pokoli  I tried with csv file from url what you guys provide as sample named `normal.csv` now got error like : 

`Unable to auto-detect delimiting character; defaulted to ','`

**Comment by pokoli** [comment] 2017-06-14 08:08
@osmangoninahid and which is the type of the file variable?

**Comment by pokoli** [comment] 2017-07-03 07:40
I'm closing the issue as I understand that it was a wrong input and it was correctly fixed. 
If not, feel free to reopen it. 

A

**Closed by pokoli** 2017-07-03 07:40 UTC

**Comment by kumaran6667** [comment] 2017-09-04 14:52
Hi 
I got the same error. below is my code and i attached the log trace. I am able to see the file object in console as well. but papa parse throws error. pls help.
![capture](https://user-images.githubusercontent.com/31625438/30031317-7d517916-91ae-11e7-9f18-decd54b7c660.PNG)

onChange($event) {
          try{
          var file = $event.target.files[0];
          console.log(file);
           Papa.parse(file, {
             header: true,
             complete: function(results) {
                console.log(results);
             }
           });

**Comment by pokoli** [comment] 2017-09-04 15:30
HI @kumaran6667,

Which is the value of $Event.target.files[0]?

Could you provide some example steps in order to reproduce the error?

**Comment by kumaran6667** [comment] 2017-09-05 08:42
@pokoli it is a file Object. I did console log of that object.refer attachment.
Actually it is a csv file imported from UI. below is the code for import.
<input type="file" (change)="onChange($event)" multiple />
Mine is angular2 project and installed using npm install --save babyparse
![capture2](https://user-images.githubusercontent.com/31625438/30052744-240fd352-9244-11e7-9a0c-c624b24427ab.PNG)

**Comment by pokoli** [comment] 2017-09-05 08:44
@kumaran6667 baby parse is not intended for browser usage. 

You should install PapaParse (which is available on npm too)

**Comment by kumaran6667** [comment] 2017-09-05 09:26
thank you.. it works with papaparse. i gave the command npm install papaparse.
but in the below mentioned npm page command given is npm install babyparse. Please correct it if that is wrong because it helps others.
https://www.npmjs.com/package/papaparse

**Comment by pokoli** [comment] 2017-09-05 09:42
@kumaran6667 I've removed the babyparse reference in b263e90d7f0d5884d64d5fecdf15a6ad0698109f and also published a new version (which contains another fix) to reflect the changes on npm

**Comment by pokoli** [comment] 2017-09-05 09:42
thanks for the suggestion.

**Comment by kumaran6667** [comment] 2017-09-05 09:47
awesome :)
