### ISSUE TITLE
parsing gets wrong if first line begins with a comma

### ISSUE THREAD

**Issue by clombardi** [mholt/PapaParse#685] opened 2019-06-24 14:55 UTC
Just check the following:
```
papa.parse(',"a","b"\n,,"c","d,e",,34,')
```
The delimiter is the comma, this is OK. But the parsed first line includes just one column that encompasses the whole string `',"a","b"'` 

The problem seems to happen with the first line only, leading commas in subsequent lines make no hassle.

In the program where I use papaparse, I fixed this problem by adding a leading `""` if the string starts with a comma, hence I get
```
papa.parse('"","a","b"\n,,"c","d,e",,34,')
```
which works OK

**Comment by georgeslabreche** [comment] 2019-06-24 22:47
I am also encountering this issue. I am working around it by setting the header option to false, manually skipping the header row, and accessing data with array indices.

**Comment by pokoli** [comment] 2019-06-25 07:11
OK, so i close this issue as duplicate of #675

**Comment by clombardi** [comment] 2019-06-25 14:20
... if you consider that the two issues refer to the same problem, it is
OK, whenever you fix it in some future version. I had checked #675, it was
not clear to me whether it raised the same issue that happened to me. I
take the opportunity to congratulate the Papaparse team, is a very nice
tool. Cordially - Carlos Lombardi

**Comment by seth-shaw-unlv** [comment] 2019-07-06 00:00
I don't believe this is the same issue as #675. I have also run into this issue where, when the first value of the first row is blank, it fails to parse.

For example, the spreadsheet
```
,myfile.jpg,My nice image,2019-07-01?,"A fine image, yes?",Do whatever you want with it.,There's only one image.,29;28,Anonymous,,
,anotherFile.tif,My Kool Picture,2019-07-02,A kool picture.,Public Domain,55 mb,27;28,,,
,,,,,,,,,,
```
does not parse correctly:
![Screen Shot 2019-07-05 at 4 43 56 PM](https://user-images.githubusercontent.com/29869988/60748730-d9f85080-9f45-11e9-98a8-9bdeb3d2eb1f.png)

but changing the first value of the first row to a non-blank value (e.g. "b") causes the parser to work correctly:
![Screen Shot 2019-07-05 at 4 41 05 PM](https://user-images.githubusercontent.com/29869988/60748744-feecc380-9f45-11e9-9a0e-9ca3906cf071.png)

I've tested this with the [current master version](https://github.com/mholt/PapaParse/blob/master/papaparse.js) as [mentioned in the other issue thread](https://github.com/mholt/PapaParse/issues/675#issuecomment-506947859) but the error persists.

**Comment by seth-shaw-unlv** [comment] 2019-07-15 19:47
@pokoli, can we please reopen this issue?

**Comment by dboskovic** [comment] 2019-07-22 06:01
This issue is caused by the condition on line 1427 - it falsely infers that the entire format must be unquoted and switches to `fastMode` which is a very basic parser. If we disable switching to `fastMode` in this case it should resolve the issue.

A test case should be added for this. PRs welcome!

https://github.com/mholt/PapaParse/blob/master/papaparse.js#L1427-L1430

**Comment by martinffoster** [comment] 2019-09-11 04:01
I tripped across this bug today.  This note is to add another test case: it occurs on any row starting with the delimiter.  Eg with `header: true`:

OK:
```
Column 1,Column 2,Column 3,Column 4
1-1,1-2,1-3,1-4
1-2,2-2,2-3,2-4
```
error:
```
Column 1,Column 2,Column 3,Column 4
,1-2,1-3,1-4
1-2,2-2,2-3,2-4
```
error:
```
Column 1,Column 2,Column 3,Column 4
1-1,1-2,1-3,1-4
,2-2,2-3,2-4
```
error:
```
Column 1,Column 2,Column 3,Column 4
,1-2,1-3,1-4
,2-2,2-3,2-4
```
The header row always gets correctly parsed. 
The error is all the same, a variant of:
```
{type: "FieldMismatch", code: "TooFewFields", message: "Too few fields: expected 4 fields but parsed 1", row: 2}
code: "TooFewFields"
message: "Too few fields: expected 4 fields but parsed 1"
row: 2
type: "FieldMismatch"
__proto__: Object
```

**Comment by tuananh** [comment] 2020-03-16 14:07
Ah i get the same issue. is there any workaround ?

**Closed** 2020-05-01 17:37 UTC
Labels: confirmed bug, pr open
