### ISSUE TITLE
Unparse is removing zeros before a string

### ISSUE THREAD

**Issue by medasani5** [mholt/PapaParse#767] opened 2020-02-25 01:30 UTC
I am, using a papaparse of version 4.6.3.I have value in array as "0001".But its displayed as "1" when array is converted to csv format.
Similarly another value in array "05" is displayed as "5" .

**Comment by pokoli** [comment] 2020-02-25 08:25
Did you have the dynamic typic setting activated?

**Comment by dmoskovtsov** [comment] 2021-03-03 09:26
Experiencing the same issue. Default setting. Tried 5.1.1 and 5.3.0

`
const products = { barcode: '077',  name:   'my product'}

Papa.unparse(products)`

Results in CSV with "77"

**Comment by dmoskovtsov** [comment] 2021-03-04 03:24
@medasani5 I experienced a similar issue. In my case, the problem was Mac's Numbers app that was stripping off zeros and not ParaRarse.

**Comment by pokoli** [comment] 2021-03-04 08:51
If you are opening CSV the files in SpreadSheet software it is common that they try to convert strings to numbers if you do not explicity tell that the colum is of type of text.

I'm closing this because is one year old without any further feedback. I will assume the case was related to spreadsheet software. 
Please reopen with an scenario to reproduce the issue if you don't agree. 

Thanks @dmoskovtsov for the feedback!

**Closed by pokoli** 2021-03-04 08:51 UTC
