### ISSUE TITLE
When using webworker cursor position isn't updated

### ISSUE THREAD

**Issue by desean1625** [mholt/PapaParse#536] opened 2018-07-11 14:44 UTC
The below outputs the progress events as expected enabling a progress bar
```js
Papa.parse(file, {
  delimiter: settings.csv.delimiter,
  newline: settings.csv.newline,
  quoteChar: settings.csv.quoteChar,
  //worker: true,
  step: function(row, parser) {
    if (row.meta.cursor % 20000 === 0) {
      console.log({ progress: Math.round(row.meta.cursor / file.size), t: "PROGRESS" });
    }
  }
})
```
when I turn the web worker on the cursor position is at the end of the file always.

```js
Papa.parse(file, {
  delimiter: settings.csv.delimiter,
  newline: settings.csv.newline,
  quoteChar: settings.csv.quoteChar,
  worker: true,
  step: function(row, parser) {
    if (row.meta.cursor % 20000 === 0) {
      console.log({ progress: Math.round(row.meta.cursor / file.size), t: "PROGRESS" });
    }
  }
})
```

**Comment by pokoli** [comment] 2018-07-26 13:01
This is a duplicate of #465

**Closed by pokoli** 2018-07-26 13:01 UTC

**Comment by victorlucss** [comment] 2020-08-11 16:25
Since 2018 without response :(
