### ISSUE TITLE
transformHeader does not pass column index

### ISSUE THREAD

**Issue by cfjedimaster** [mholt/PapaParse#844] opened 2020-11-21 17:34 UTC
As the title says, when I use transformHeader, I get the column name, but not the index.

**Comment by pokoli** [comment] 2020-11-21 17:41
Probably you are using the wrong version. This feature was released on papaparse 5.3.0

I'm closing this issue, please provide more info if you don't agree

**Closed by pokoli** 2020-11-21 17:41 UTC

**Comment by cfjedimaster** [comment] 2020-11-21 17:42
I'm using 5.3. Here is a CodePen. https://codepen.io/cfjedimaster/pen/zYBVWLY?editors=1111 

Note I don't use the index in my code so you will need to fork and edit, but when I did, it wasn't being passed.

**Comment by pokoli** [comment] 2020-11-21 17:51
Please provide an example to reproduce the issue. 
For me it is working as there is a test that ensures the behaviour:

https://github.com/mholt/PapaParse/commit/ce858b3c414236e52de05e2d0285e08ef2272e0a

**Comment by cfjedimaster** [comment] 2020-11-21 18:04
I forked it and modded the function to use both arguments - idx is undefined.

https://codepen.io/cfjedimaster/pen/eYzwrBp?editors=1011

**Comment by djave-co** [comment] 2021-01-20 10:41
I think I have solved this, it works for me if you remove `.min` from the CDN link. It may be that the tests are not run on the production code / the production code wasn't minified in the latest release.
