### ISSUE TITLE
Is PapaParse 4.5.0 supported in browser?

### ISSUE THREAD

**Issue by thaoula** [mholt/PapaParse#517] opened 2018-06-04 13:08 UTC
Hi Guys,

Is PapaParse 4.5.0 still supported in browser? 

We get the following error when building using Angular CLI 6.0.5 -

ERROR in ./node_modules/papaparse/papaparse.min.js[39m[22m[0m
2018-06-04T12:54:43.4234387Z [0m[1m[31mModule not found: Error: Can't resolve 'stream' in 'node_modules/papaparse'[39m[22m[0m

Downgrading to version 4.4.0 works fine.

Regards,
Tarek

**Comment by pokoli** [comment] 2018-06-04 13:47
Hi Tarek, 

This code was introduced on https://github.com/mholt/PapaParse/commit/392408edcc4d03d6e30aa80fffa1982231cd1303

It is expected that this code is not run on the browser so the require should not be executed on any browser version and it should never fail. 

When do you get this error?

**Comment by timbru31** [comment] 2018-06-04 14:11
I'm getting the same error when upgrading to v4.5.0. Webpack throws this error when compiling the Angular app.

**Comment by pokoli** [comment] 2018-06-04 14:13
Sorry but I'm not so much familiar with webpack. Is there any way to make it skip this kind of errors or to tell that this code will be never executed on browser?

**Comment by timbru31** [comment] 2018-06-04 14:16
Seems this might be an issue with Angular-CLI v6, too: https://github.com/angular/angular-cli/issues/10681 
I'll keep debugging and update my response if I find any clues 🔍

**Comment by pokoli** [comment] 2018-06-04 14:18
@timbru31 If you find any workaround let us know and will try to include it in a bug fix release if possible

**Comment by jefbarn** [comment] 2018-06-07 00:13
workaround is add readable-stream module as a substitute for stream.
Alias in tsconfig.json:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "stream": [
        "node_modules/readable-stream"
      ]
    },
```

**Comment by eitacode** [comment] 2018-06-07 21:40
@jefbarn thanks for the tip but that didn't work for me.  In return I get an error like this

`Error: Can't resolve '.... /node_modules/readable-stream' in '... /node_modules/papaparse'`

**Comment by manish2237** [comment] 2018-06-14 09:49
This is the actual workaround...

`  "paths": {
      "@fuse": [
        "@fuse/"
      ],
      "stream": [
        "../node_modules/readable-stream"
      ]
    },`

**Comment by dawidrylko** [comment] 2018-06-15 07:56
agree with @manish2237

**Comment by pokoli** [comment] 2018-06-15 08:04
So we agree that we can close this issue [with the proposed solution](https://github.com/mholt/PapaParse/issues/517#issuecomment-397238277 )?

**Comment by timbru31** [comment] 2018-06-15 08:41
While this might solve the issue, the underlying change is in Angular CLI 6+ (see https://github.com/angular/angular-cli/issues/9827#issuecomment-369578814)
As a workaround without an extra dependency, you can patch the webpack config like this: https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d

**Comment by pokoli** [comment] 2018-06-21 11:59
I'm closing this issue as I understand that we don't have to do anything in PapaParse as this is an Angular issue and several workarrounds have been proposed already. 

Thanks to all who contributed to this issue.

**Closed by pokoli** 2018-06-21 11:59 UTC

**Comment by jefbarn** [comment] 2018-06-21 14:00
@pokoli I would say that the underling issue is that PapaParse is trying to use non-browser features in a browser context. While most front-end packaging systems can work around this, the Angular team took a hard line and is refusing to support loading node features into the browser.
I think the correct answer is to have separate node and browser builds if the intent is not to support streams in the browser, or to specifically load a stream library that can be used in either context (readable-stream).

**Comment by Rutulpatel7077** [comment] 2018-08-02 14:53
I faced same error in React Native! any solution ?

**Comment by mitutee** [comment] 2018-08-22 10:46
@Rutulpatel7077 unfortunately, this workaround is not tracked by git.
@pokoli 4.5.0 became incompatible with react-native. I hoped this library not to have any platform specific dependencies.

**Comment by Rutulpatel7077** [comment] 2018-08-22 11:56
@mitutee  Instead of using node_module you can put all files in your project and use papaparse fro mthere

**Comment by Lingyis** [comment] 2018-08-22 14:03
my solution is to just downgrade to 4.4 like those before me mentioned.  for me it's perfectly fine, i only use a very limited set of features.

**Comment by Rutulpatel7077** [comment] 2018-08-22 14:17
@Lingyis Good to know!
Otherwise, `Install stream` as I mentioned above and copy the PapaParse folder from node_modules to your root of the project and `import Papa from 'from you folder path'`

I can run every feature of PapaParse.

**Comment by pokoli** [comment] 2018-08-22 16:07
@mitutee indeed the dependency is optional and not required to run on other plataforms. 

The issue is that react-native does not detect it as optional and complains about it.

**Comment by btakita** [comment] 2018-10-01 03:59
I'm having the same issue with sapper & rollup. I'd rather not use the "workaround" because 'stream' is not necessary in the browser.

Another workaround that could be used is to vendorize PapaParse. However, it would be great if dependencies on this project were able to be sorted out.

**Comment by arxpoetica** [comment] 2018-10-07 02:18
Having the same issue as @btakita and hoping for PapaParse to resolve its dependency issues. To be clear, it appears, as @jefbarn said above:

> I would say that the underling issue is that PapaParse is trying to use non-browser features in a browser context. [.i.e., the stream module, which is native only to Node]

@pokoli can this be fixed in PapaParse itself?

**Comment by pokoli** [comment] 2018-10-08 07:41
@arxpoetica how do you propose to fix it? 

For me there is no dependency problem as the code only uses then library when available, so if you are on the browser and the library is not available it won't use it.

**Comment by jefbarn** [comment] 2018-10-08 08:49
@pokoli the problem is that modern code bundling tools don’t ignore the offending require and instead report an error. A simple fix could be to refactor the code slightly to have a browser build that omits the require and list it under the browser tag in package.json

**Comment by pokoli** [comment] 2018-10-08 08:54
@jefbarn if I understand correctly this mean having two PapaParse packages? Or a single one?

I'm happy to see a PR that implements this refactor and test it. It should not be so hard as there is only one line with a ofending package.

**Comment by jefbarn** [comment] 2018-10-08 09:00
It would be one npm package with two different .js entry points depending on context. I’ll work on a PR tomorrow.

**Comment by jefbarn** [comment] 2018-10-08 18:54
See PR #580
