### ISSUE TITLE
npm install and test lead to errors

### ISSUE THREAD

**Issue by darianhickman** [mholt/PapaParse#312] opened 2016-05-06 01:01 UTC
mocha: command not found

npm ERR! Darwin 15.3.0
npm ERR! argv "/usr/local/Cellar/node/0.12.0/bin/node" "/usr/local/bin/npm" "run" "test-node"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! papaparse@4.1.2 test-node: `mocha tests/node-tests.js tests/test-cases.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the papaparse@4.1.2 test-node script 'mocha tests/node-tests.js tests/test-cases.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the papaparse package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     mocha tests/node-tests.js tests/test-cases.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs papaparse
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls [papaparse](url)
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/darianhickman/Documents/DataBrowser/vendor/PapaParse/npm-debug.log
npm ERR! Test failed.  See above for more details.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

**Comment by kramsee** [comment] 2016-05-08 14:00
It looks like **mocha** is missing when you run `npm test`.

    npm WARN Local package.json exists, but node_modules missing, did you mean to install?

Can you confirm that you have a node_modules folder inside the papaparse folder?

**Comment by pokoli** [comment] 2017-01-10 16:54
I can not reproduct it anymore on latest version so I'm closing the issue

**Closed by pokoli** 2017-01-10 16:54 UTC
