### ISSUE TITLE
meta.cursor value is incorrect if you use parser.pause() and parser.resume() in step function

### ISSUE THREAD

**Issue by Bunlong** [mholt/PapaParse#768] opened 2020-02-29 17:40 UTC
I am using PapaParse the latest version `5.1.1`.

I'm trying to make use of `meta.cursor` to display a progress bar as well. The following example works fine:

```javascript
Papa.parse(file, {
    step: function(results, parser){
        // This gives expected result for cursor
        console.info(result.meta.cursor);
     }
}
```

But when I make use of `parser.pause()` and `parser.resume()` the value for `meta.cursor` is incorrect.

```javascript
Papa.parse(file, {
    step: function(results, parser){
        // This does not give the correct value for cursor
        console.info(result.meta.cursor);
        parser.pause();
        parser.resume();
    }
}
```

 Could you please kindly check? Thanks!

**Comment by pokoli** [comment] 2020-03-02 09:21
I'm closing this as duplicate of #321

**Closed by pokoli** 2020-03-02 09:21 UTC
