### ISSUE TITLE
Parsing issue on large file: 5.4 update

### ISSUE THREAD

**Issue by allonzy** [mholt/PapaParse#984] opened 2023-03-21 07:45 UTC
This is a reproduction of a bug I've encounter with real data I can't share here 

``` 
let papa = require("papaparse")
let fs = require("fs");
let expected = {
  key1: 'FOO',
  key2: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae',
  key3: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae',
  key4: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae',
  key5: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae',
  key6: '2022-03-28T10:51:32.0000000+01:00',
  key7: 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque id neque eget urna venenatis volutpat a at ex. Aliquam tellus magna, convallis et varius a, commodo quis ante. Morbi a diam sit amet magna laoreet tincidunt eget id leo. Pellentesque sollicitudin mauris vel metus consectetur, id egestas eros'
}

first = true
let i = 0;
papa.parse(fs.createReadStream('./papaparse_bug.csv'),{
  header: true,
  delimiter: '\t',
  step: async (results, parser) => {
    i ++;
    if(JSON.stringify(results.data) !== JSON.stringify(expected) && first === true){
      console.log(results.data,i)
      first = false
    }
  }
})
```

At line 130, only on version 5.4 i have data that don't match with expected, the file consist of only the same data repeated a lot. 

> {
  key1: 'FOO',
  key2: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae',
  key3: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae_1',
  key4: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae_2',
  key5: 'bc4be155-aaa8-4f66-8f02-91c4c517c9ae_3',
  key6: '2022-03-28T10:51:32.0000000+01:00',
  key7: 'Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque id neque eget urna venenatis volutpat a at ex. Aliquam tellus magna, convallis et varius a, commodo quis ante. Morbi a diam sit amet magna laoreet tincidunt eget id leo. Pellentesque sollicitudin mauris vel metus consectetur, id egestas eros'
}

**Comment by pokoli** [comment] 2023-03-21 07:48
Duplicate of #980 which is fixed on master

**Closed by pokoli** 2023-03-21 07:48 UTC
