### ISSUE TITLE
delimiter autodetect collides with comments 

### ISSUE THREAD

**Issue by griii2** [mholt/PapaParse#334] opened 2016-08-23 13:28 UTC
If you configure the parser as

`delimiter: "", // auto-detect,
comments: true`

and there is a comment in the first line that contains possible delimiter then it is incorrectly detected as a delimiter

Example data:
//this, is a first line comment, with some commas, right?
this;is;data;using;semicolon;as;delimiter

Result: 
detected delimiter is comma, not semicolon

**Comment by pokoli** [comment] 2018-04-16 08:00
I'm closing this as duplicate of #489, because a workarround has been posted there.

**Closed by pokoli** 2018-04-16 08:00 UTC
