### ISSUE TITLE
How can I use Papa in react-native?

### ISSUE THREAD

**Issue by qpjtmdnft** [mholt/PapaParse#530] opened 2018-07-03 02:55 UTC
I use npm to install papa in my project and use it like this:
const papa = require('papaparse');

but the result is this:
![image](https://user-images.githubusercontent.com/4716722/42196223-67b03a40-7eaf-11e8-9a6a-c08f21513104.png)

So am I use it in a wrong way? Right way is what?

**Comment by pokoli** [comment] 2018-07-17 20:38
I'm closing this as duplicate of #517 Reopen it if you don't agree

**Closed by pokoli** 2018-07-17 20:38 UTC
