### ISSUE TITLE
error callback is not called

### ISSUE THREAD

**Issue by sandeep45** [mholt/PapaParse#328] opened 2016-07-27 17:58 UTC
My CSV has a "TooFewFields" error in one of the rows, but the error callback is not called. When is this callback called?

**Comment by Sidd27** [comment] 2016-08-27 17:25
Can you please send the file, It will be easier to reproduce

**Comment by pokoli** [comment] 2017-01-11 08:50
I'm closing this because no futher information have been provided in 6 month. Re open with a steps to reproduce scenario if you don't agree.

**Closed by pokoli** 2017-01-11 08:50 UTC
