### ISSUE TITLE
Auto detection bug appearing between 4.6.2 and 4.6.3

### ISSUE THREAD

**Issue by fdeslandes-wk** [mholt/PapaParse#642] opened 2019-03-05 18:43 UTC
Hi, I will provide a CSV which auto detected semi-colon as the separator in 4.6.1 (what I thought was the expected behavior) and started detecting comma in 4.6.3.

It works as expected on the demo page because the demo page is still on the 4.6.1 version.

Here is csv content to reproduce the issue:
```
[Hartmann, Callie|0|0];"";"";""
T2125[1].Fed.Toabua672;"12.00";"";"Any GST/HST, provincial sales tax, returns, allowances, discounts, and GST/HST adjustments (included on line 8) and any WIP at the end of the year you elected to exclude (see Chapter 2 of Guide T4002)"
```

**Comment by pokoli** [comment] 2019-03-06 08:18
For me it is a duplicate of #617

**Closed by pokoli** 2019-03-06 08:18 UTC

**Comment by fdeslandes-wk** [comment] 2019-03-06 14:00
@pokoli It does not need the `header` option to true to be reproduced.

**Comment by pokoli** [comment] 2019-03-06 15:02
@fdeslandes-wk Yes but I think the issue is unrelated to header option
