### ISSUE TITLE
big file results only return a few lines

### ISSUE THREAD

**Issue by Sergiodiaz53** [mholt/PapaParse#213] opened 2015-06-03 09:53 UTC
Hi,

This is my first time using Papaparse so maybe I'm doing it wrong but even reading and reading the information and demos I'm having a problem with big files.

I need to read csv files (from few kbs to 1Gb max size) which have a 'header' and the the info, they are like:

filename : whatever
filesize : whatever
root : whatever
==============
INFO, info, number, number, info
INFO, info, number, number, info
...

I have implemented papaparse (great job, speed is amazing) and it works fine in small files (few mb) but when I try to use a 300Mb file it appears to read it fine but in the results.data received in 'complete' the array only has the last [103166] lines of the file when the original file has 5.253.253 lines.

What is papaparse doing with the rest of the lines? I suppose that an stream will fix this but if I really need to work with all the lines at the same time so I don't know how to it...

Thanks in advance for your help.

**Comment by mholt** [comment] 2015-06-03 13:49
Would love to see your code.

**Comment by bluej100** [comment] 2015-06-03 14:59
This is a duplicate of https://github.com/mholt/PapaParse/issues/179 , neh? Are you on 4.1.1, @Sergiodiaz53 ?

**Comment by mholt** [comment] 2015-06-23 17:09
@Sergiodiaz53 If this is still an issue, feel free to re-open.

**Closed by mholt** 2015-06-23 17:09 UTC
