### ISSUE TITLE
Error when delimiter in quote, with space after delimiter

### ISSUE THREAD

**Issue by potatozerg** [mholt/PapaParse#829] opened 2020-09-17 21:48 UTC
#528 Related issue
I understand that the reason this failed is that we can't have space between delimiter and quote. Is there any way to fix it?

Sample CSV:
"Index", "Item", "Cost", "Tax", "Total"
1, "Fruit of the Loom Girl's Socks", 7.97, 0.60, 8.57
2, "Rawlings Little League Baseball", 2.97, 0.22, 3.19
3, "Secret Antiperspirant", 1.29, 0.10, 1.39
4, "Deadpool DVD", 14.96, 1.12, 16.08
5, "Maxwell House Coffee 28 oz", 7.28, 0.55, 7.83
6, "Banana Boat Sunscreen, 8 oz", 6.68, 0.50, 7.18
7, "Wrench Set, 18 pieces", 10.00, 0.75, 10.75
8, "M and M, 42 oz", 8.98, 0.67, 9.65
9, "Bertoli Alfredo Sauce", 2.12, 0.16, 2.28
10, "Large Paperclips, 10 boxes", 6.19, 0.46, 6.65

The testing data has space before the quote. So row 6, 7, 8, 10 will be parsed into 6 columns instead of 5.

**Comment by pokoli** [comment] 2020-09-18 13:00
I'm closing this as duplicate of #528 

It will be great if somebody can contribute a PR that fixes it.

**Closed by pokoli** 2020-09-18 13:00 UTC
