### ISSUE TITLE
option to trim cells /or configurable preprocessor

### ISSUE THREAD

**Issue by cocogorilla** [mholt/PapaParse#323] opened 2016-07-13 19:44 UTC
I have a situation where I'm parsing files that may or may not have whitespace after delimiters in headers and possibly between cells as well.

If I could assign a preprocessor to trim front and end between delimiters (unless explicitly contained within whitespace, that might work.

For example:
CustomerName, CustomerAddress
James T Kirk,1200 Galaxy Drive
"McCoy, Leonard ", Timbuktu

The meta demonstrates that it has inferred a column name of " CustomerAddress" and " Timbuktu" as McCoy's address.

If I could insert a "trim" directive for each cell I would get what I'm looking for, which is of course:
"CustomerName" and "CustomerAddress" as headers.
"McCoy, Leonard " and "Timbuktu" as second row data values.

**Comment by pokoli** [comment] 2017-01-16 11:51
I'm closing this as duplicate of #361 Re-open it if you don't agree.

**Closed by pokoli** 2017-01-16 11:51 UTC
