### ISSUE TITLE
Quoted delimiter in header still parsed if using a custom quote character

### ISSUE THREAD

**Issue by nsylv** [mholt/PapaParse#529] opened 2018-06-28 14:12 UTC
Sample input:
```
this,'is,a',test
1,2,3
4,5,6
```

Parsed using:
```
Papa.parse(file, {
  delimiter: ',',
  quoteChar: "'",
  escapeChar: '"',
  header: true,
  preview: 10,
  chunk: (results, handle) => {
    handle.abort();
    console.log(results);
  }
})
```

Expected output:
3 columns: `this` `is,a` and `test`

Observed output:
4 columns: `this` `'is` `a'` and `test`

***

Note that if the input is:
```
this,"is,a",test
1,2,3
4,5,6
```
I observe the expected output

**Comment by MonkeyDZeke** [comment] 2018-07-25 19:54
In my testing I see the following results:

```[input]
this,'is,a',test
1,2,3
4,5,6

[config]
{
  delimiter: ',',
  quoteChar: "'",
  escapeChar: '"',
  header: true
}

[output]
[
  {
    'this': '1',
    'is,a': '2',
    'test': '3'
  },
  {
    'this': '4',
    'is,a': '5',
    'test': '6'
  }
]
```

Note that if I invert the use of single and double quotes in the input and in the setting of `quoteChar` and `escapeChar` it still parses without error as expected. This appears to be the expected behavior according to the documentation for those settings, and the opposite of what you seem to be observing in your example. Are you still seeing this behavior, and can you give more details which might help replicate it?

**Comment by dboskovic** [comment] 2018-08-09 08:05
@nsylv can you confirm you're testing with the latest version? It looks like this issue may have been resolved.

**Comment by nsylv** [comment] 2018-08-09 08:50
yeah, after testing myself on the latest version it seems like I am seeing similar results as MonkeyDZeke - sorry for the confusion!

**Comment by pokoli** [comment] 2018-08-09 14:17
Ok, so I'm closing this issue.

**Closed by pokoli** 2018-08-09 14:17 UTC
Labels: help wanted
