### ISSUE TITLE
input substr is not a function

### ISSUE THREAD

**Issue by kumaran6667** [mholt/PapaParse#412] opened 2017-09-04 14:54 UTC
Hi @pokoli 
I got the error. below is my code and i attached the log trace. I am able to see the file object in console as well. but papa parse throws error. pls help.
![capture](https://user-images.githubusercontent.com/31625438/30031427-fae3ddd8-91ae-11e7-9b67-889a9e66e9cd.PNG)

onChange($event) {
try{
var file = $event.target.files[0];
console.log(file);
Papa.parse(file, {
header: true,
complete: function(results) {
console.log(results);
}
});

**Comment by pokoli** [comment] 2017-09-04 15:29
HI @kumaran6667, 

Which is the value of $Event.target.files[0]? 

Could you provide some example in order to reproduce the error?

**Comment by pokoli** [comment] 2017-09-04 15:30
I'm closing this as duplicate of #389, so please continue the discussion there.

**Closed by pokoli** 2017-09-04 15:30 UTC
