### ISSUE TITLE
unparse,  header is  always  included.  even if  header : false, 

### ISSUE THREAD

**Issue by alpastar** [mholt/PapaParse#436] opened 2017-11-19 11:54 UTC
unparse, header is  always  included.
is this  bug ? 

the  diifference  between demo  and my code is  that 
data is  array of object  rather than array of array ( which  is demo)

in mycase  setting fields is mandatory , 
but  specifing fields and/or  not specifing fields has no difference.
header is always included 

var csv = Papa.unparse({
	fields: ["foo", "bar"],
	data: [
		{"foo":"foo",  "bar": "aaa"},
		{"foo":'ggg", "bar: "bbb" }
	],
       config:{
          delimiter: ",",
           header : false,            //  but, always  header included   
           newline: "\n",
           skipEmptyLines:true
    }
});

**Comment by pokoli** [comment] 2017-11-20 08:30
Probably is a missing feature. I will be happy to accept a Pull Request that implements it.

**Comment by Devil-Boy** [comment] 2017-12-12 16:49
According to the docs, the config object should be a second argument to the unparse() function. It looks like you have it as a value inside of the data object. Are any of the other config options working for you?

**Comment by pokoli** [comment] 2018-05-02 15:02
I'm closing this issue as I see there is test that verifies it:

https://github.com/mholt/PapaParse/blob/30f8a397017473005d136e17e7fd65152dc7a1fe/tests/test-cases.js#L1401

So the problem is that you are not passing correctly the config. Re-open if you don't agree.

**Closed by pokoli** 2018-05-02 15:02 UTC
Labels: enhancement, help wanted, unparser

**Comment by pbaldridge** [comment] 2019-06-28 15:25
I could be mistaken, but it seems this was closed based on reviewing documentation instead of actually attempting to duplicate the issue. I have the exact same issue and am passing the config as the second option. not a value inside the data object. Perhaps this should be re-opened. Did anyone actually verify this works as designed?

**Comment by pokoli** [comment] 2019-07-01 12:42
@pbaldridge could you share a simple example to reproduce it?
