### ISSUE TITLE
Issue when parsing .csv file uploaded from a Windows machine

### ISSUE THREAD

**Issue by gayanz** [mholt/PapaParse#518] opened 2018-06-07 11:42 UTC
Windows seems to be changing MIME-Type of the csv file, to "application/vnd.ms-excel". And Papa parse returns an error for this scenario. But when file extension changed to .txt it works fine. Please refer the error message below.

Debug: internal, implementation, error 
    ReferenceError: Uncaught error: FileReaderSync is not defined
    at ....
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

Thanks.

**Comment by pokoli** [comment] 2018-06-07 11:43
Could you please include a file to reproduce the issue?
Are you reading it from browser or from node? 
Which config are you using?

**Comment by gayanz** [comment] 2018-06-08 10:28
@pokoli It's just a file upload done in front end (AngularJs) and Papa parse is used in backend (NodeJs).

Front end: 
``   var url = "/api/importUsers";
      var fd = new FormData();
      var files = document.getElementById('file-upload').files[0];
      fd.append('file',files);

      $http.post(url, fd, {
        transformRequest: angular.identity,
        headers: {'Content-Type': undefined}
      }).success(function(response){
       // success 
     }).error(function(response) {
       // error
     });``


Back end: 
`` var papa = require('papaparse');
    var users = papa.parse(req.payload.file,{header:true,delimiter:',',skipEmptyLines: true});``

**Comment by gayanz** [comment] 2018-06-11 07:47
@mholt, @pokoli Am I doing something wrong here? Please advise. 
Thanks.

**Comment by pokoli** [comment] 2018-06-11 07:48
This is a duplicate of #466

**Closed by pokoli** 2018-06-11 07:48 UTC
